apiVersion: v1
kind: Service
metadata:
  name: mongodb 
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017 
      targetPort: 27017 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo 
    spec:
      containers:
        - name: mongo-container
          image: mongo 
          ports:
          - containerPort: 27017 


