apiVersion: v1
kind: Service
metadata:
  name: pingout
spec:
  type: LoadBalancer
  ports:
    - port: 80 
      targetPort: 5000
  selector:
    app: pingout 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pingout-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pingout
    spec:
      containers:
      - name: pingout-container
        image: gcr.io/udemy-210200/pingout:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"


